# Generated by Django 5.2.1 on 2025-06-02 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventgroup",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="eventgroup",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
